//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XNK
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barcode
    {
        public string Variant { get; set; }
        public string SUPPLIER { get; set; }
        public string POKhach { get; set; }
        public string PO { get; set; }
        public Nullable<int> OuterPacks { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> TotalPallets { get; set; }
        public string Barcode1 { get; set; }
        public Nullable<double> Bricks { get; set; }
        public string Productcode { get; set; }
        public string ProductNumber { get; set; }
        public string SuppliesName { get; set; }
        public Nullable<double> Box { get; set; }
        public string duoimau { get; set; }
        public string loca { get; set; }
    }
}
